development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  host: localhost
  pool: 5
  username: steve
  password: ZaQ1@wSx

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  host: localhost
  pool: 5
  username: steve
  password: ZaQ1@wSx

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  host: localhost
  pool: 5
  username: steve
  password: ZaQ1@wSx
